spring.application.name=inventarios
# Conexión a mysql
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#Configurar el patrón del log (en lugar de logback-spring.xml)
logging.patter.console=[%thread] %-5level: %logger - %msg%n
#Configurar el nivel de log (INFO)
logging.level.root=INFO
#Opcional, configurar niveles por paquetes
#logging.level.gm.inventarios=DEBUG
#logging.level.org.springframework=WARN
#Cambiar el puerto Tomcat
#server.port=8080
spring.main.banner-mode=off
